default:
  image: node

variables:
  PRODUCTION_DOMAIN: buzzally.surge.sh
  STAGING_DOMAIN: buzzally-staging.surge.sh
  REVIEW_DOMAIN: buzzally-$CI_ENVIRONMENT_SLUG.surge.sh

stages:
  - build
  - test
  - deploy review
  - deploy staging
  - deploy production
  - production tests

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull

skiped job: # this job do not execute using .
  stage: build
  # allow_failure: true
  # when: manual
  cache: {}
  variables:
    TEST_VARIABLE: "Test"
    VARIABLE_FROM_VARIABLE: $PRODUCTION_DOMAIN
  script:
    - echo "$TEST_VARIABLE" and "$PRODUCTION_DOMAIN" and $VARIABLE_FROM_VARIABLE

build:
  stage: build
  before_script:
    - npm install
    - npm install -g gatsby-cli
  script:
    - gatsby build
    - echo $CI_COMMIT_SHORT_SHA
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
  artifacts:
    paths:
      - ./public

test build:
  image: alpine
  stage: test
  cache: {}
  script:
    - grep -q "Gatsby" ./public/index.html

test serve:
  stage: test
  before_script:
    - npm install
    - npm install -g gatsby-cli
  script:
    - gatsby serve &
    - sleep 10
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"

deploy review:
  stage: deploy review
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$REVIEW_DOMAIN
    on_stop: stop review
  cache: {}
  only:
    - merge_requests
  before_script:
    - npm install --global surge
  script:
    - surge --project ./public --domain $REVIEW_DOMAIN

stop review:
  stage: deploy review
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  cache: {}
  only:
    - merge_requests
  before_script:
    - npm install --global surge
  script:
    - surge teardown $REVIEW_DOMAIN
  variables:
    GIT_STRATEGY: none

deploy staging:
  stage: deploy staging
  environment:
    name: staging
    url: https://$STAGING_DOMAIN
  cache: {}
  only:
    - master
  before_script:
    - npm install --global surge
  script:
    - surge --project ./public --domain $STAGING_DOMAIN

deploy production:
  stage: deploy production
  environment:
    name: production
    url: https://$PRODUCTION_DOMAIN
  cache: {}
  only:
    - master
  before_script:
    - npm install --global surge
  script:
    - surge --project ./public --domain $PRODUCTION_DOMAIN

production tests:
  image: alpine
  stage: production tests
  cache: {}
  only:
    - master
  before_script:
    - apk add --no-cache curl
  script:
    - curl "https://$PRODUCTION_DOMAIN/" | tac | tac | grep -q "Gatsby"
    - curl "https://$PRODUCTION_DOMAIN/" | tac | tac | grep -q "$CI_COMMIT_SHORT_SHA"